name: DefectDojo SAST Integration
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  run-integration:
    runs-on:
      - runs-on=${{ github.run_id }}
      - runner=32cpu-linux-arm64
    steps:
      - uses: yieldstreet/defect-dojo-connector@v1.0.0
        with:
          integration_name: "sast"
          repository: ${{ github.event.repository.name }}
        env:
          DEFECT_DOJO_API_TOKEN: ${{ secrets.DEFECT_DOJO_API_TOKEN }}
          DEFECT_DOJO_API_URL: ${{ vars.DEFECT_DOJO_API_URL }}
          DEFECT_DOJO_PRODUCT_ID: ${{ vars.DEFECT_DOJO_PRODUCT_ID }}
          DEFECT_DOJO_USER_ID: ${{ vars.DEFECT_DOJO_USER_ID }}
          GITHUB_ORG: "yieldstreet"
          DEPENDABOT_CLIENT_ID: ${{ secrets.DEPENDABOT_CLIENT_ID }}
          DEPENDABOT_PRIVATE_KEY: ${{ secrets.DEPENDABOT_PRIVATE_KEY }}
          CODACY_API_URL: ${{ vars.CODACY_API_URL }}
          CODACY_API_TOKEN: ${{ secrets.CODACY_API_TOKEN }}
